### ISSUE TITLE
Handling scenario state for given input

### ISSUE THREAD

**Issue by pimjansen** [tomakehurst/wiremock#1027]
I want to have some business logic in my mocks which work pretty well with the given scenarios. The use case is that i need to run polling to ensure i get back a certain status from a backend. The status can go from:

- pending
- referred
- approved
- rejected

I can easily make some flows for example from pending to referred to approved. The only problem is this way i can only run 1 scenario at the time and as far as i can see i need to flush the scenario state manually.

Is there a way to have a state for a given input variable? For example i have to run this polling for a given order that we can register the scenario for a given orderID and that it matches the state for the given input itself?

This is the json i have at this point though:

```
{
    "scenarioName": "creditcheck",
    "requiredScenarioState": "pending",
    "newScenarioState": "approved",
    "request": {
        "method": "GET",
        "url": "/vznl/order"
    },
    "response": {
        "status": 200,
        "body": "approved"
    }
} 
```

**Comment by pimjansen** [comment]
Sorry for not being clear from the start. But indeed the second one, derive the state from an aspect of the request.

For example i can push above example for order A which follows the flow follow 1,2,3,4 but when i push order B it should ofcourse have its own scenario so also start with 1

**Comment by tomakehurst** [comment]
You should be able to do that by making your stubs more selective in their matching and using multiple scenario names.

E.g. you might match the initial order POST on some part of the request body like the customer ID (in addition to URL and method).

So you'd end up with 2 or more sets of stubs that exist in separate scenarios and don't trigger each other such as:

1:

```json
{
    "scenarioName": "creditcheck-1",
    "requiredScenarioState": "pending",
    "newScenarioState": "approved",
    "request": {
        "method": "POST",
        "url": "/vznl/order",
        "bodyPatterns": [
            { "matchesJsonPath": "$..customer[?(@.id == '123')]" }
        ]
    },
    "response": {
        "status": 200,
        "body": "approved"
    }
}
```

2:

```json
{
    "scenarioName": "creditcheck-2",
    "requiredScenarioState": "pending",
    "newScenarioState": "approved",
    "request": {
        "method": "POST",
        "url": "/vznl/order",
        "bodyPatterns": [
            { "matchesJsonPath": "$..customer[?(@.id == '456')]" }
        ]
    },
    "response": {
        "status": 200,
        "body": "approved"
    }
}
```

**Comment by brandall10** [comment]
I'm dealing with this issue as well.

I'm working why there isn't an exposed API to set scenario and state in the context of a test.  To me it makes perfect sense to have a flow as such

- Begin test
- Call into rest api that kicks off a scenario
- Run test steps - for matches that belong to a scenario, return responses in the scenario flow order
- Call into rest api to stop current scenario
- End test

Think about having 10,000 tests, and within those thousands of tests there's a /users endpoint that may return dozens of different permutations based on the context of the test - ie. sometimes you need to return just one user, sometimes you return a particular set of users based on account access control, sometimes you need to return list + 1 because a user was just added, sometimes you need to return list - 100 users that were just deleted in the previous request, etc.   

It seems to me the only way to accomplish this is to retain a table client-side that keeps an index of those states and every time one needs to be fetched that you need to reset the scenario and perform index number of requests against that endpoint prepare the endpoint to return the state needed.

Apologies if I'm misunderstanding how Scenarios works.  It seems like a great feature, but I'm having trouble seeing its utility outside of very small test suites.
