### ISSUE TITLE
Basic auth is returning 404

### ISSUE THREAD

**Issue by pimjansen** [tomakehurst/wiremock#1068]
I have a very basic test setup that can reproduce this issue. Somehow on certain endpoints i keep getting 404 responses where i actually expect a 403.

Below is my demo request what as you can see has basic auth setup.
```
{
  "request": {
    "method": "GET",
    "urlPath": "/myproject/service/validate",
    "basicAuthCredentials": {
      "username": "foo",
      "password": "bar"
    }
  },
  "response": {
    "status": 200,
    "body": "mycontent"
  }
}
```

However on this request i keep getting this response:
```
                                               Request was not matched
                                               =======================

-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
GET                                                        | GET
/myproject/service/validate                                | /myproject/service/validate
                                                           |
Authorization: Basic Zm9vOmJhcg==                          | Authorization: Basic Zm9vbzpiYXI=                   <<<<< Header does not match
                                                           |
                                                           |
-----------------------------------------------------------------------------------------------------------------------
```

Weirder thing is that i have the same at another stub where it actually works fine:
```
{
  "request": {
    "method": "GET",
    "urlPath": "/vnext/serviceability",
    "basicAuthCredentials" : {
      "username" : "foo",
      "password" : "bar"
    }
  },
  "response": {
    "status": 200,
    "bodyFileName": "vnext/serviceability/default.json",
    "headers": {
      "Content-Type": "application/json"
    }
  }
}
```

**Comment by tomakehurst** [comment]
This is a feature of how WM's matching currently works - it searches linearly through the stubs, returns the stub response if it finds one, and returns a 404 if it gets to the end of the list without a match. There's nothing in there to vary the response based on why it didn't match.

You can approximate what you're looking for though, by creating two stubs - 1) with the basic auth matcher at a higher priority and a 200 status, 2) without the basic auth, lower priority and a 403 response (same URL in both cases). That way a non-match on the auth header will mean the lower priority stub will be matched.

Since this is a question I'm closing it off. Please re-post on the mailing list if you'd like to discuss further.

**Comment by pimjansen** [comment]
Great! Could help to write something about this in the docs though but overall it is working like you mentioned
