### ISSUE TITLE
POST empty body is still matched

### ISSUE THREAD

**Issue by mbeczek** [tomakehurst/wiremock#1152]
Hi!
I'm challenging with this: I created 20k mappings (don't ask me why :) ) and I have performance issues. This is the first problem I found.
I'm checking my mappings via Postman and I'm sending empty-bodied POST request to my WireMock instance, my request matcher is quite simple:
`"request" : {
    "url" : "/myapp/api/execute",
    "method" : "POST",
    "headers" : {
      "RuleName" : {
        "equalTo" : "/someheader/2019.0/somevalue/2.0"
      }
    }
  },`
I get >30s response times. As I dig into code, I found here https://github.com/tomakehurst/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/matching/RequestPattern.java#L259 and here https://github.com/tomakehurst/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/servlet/WireMockHttpServletRequestAdapter.java#L131 that if I send empty-bodied POST, it is changed from null to zero-length byte array. This is not bad, but then in _allBodyPatternsMatch_ method WireMock needlessly do all the matching, because request body is not null (but empty!).

Is that intetional or can I make some change to this? :)

WireMock version: 2.18.0

Thanks!

**Comment by tomakehurst** [comment]
Have you profiled that bit of code, or are you speculating that it's the bottleneck?

Although you're correct that it could be short-circuited, I've seen a number of other very similar setups that get < 100ms response times with similar numbers of stubs.

I'd suggest re-testing with the latest version, as there have been some performance improvements recently (2.18.0 is quite old now).

Also, are you able to post your stub file so that I can attempt to repro?

**Comment by mbeczek** [comment]
Hi,
First of all, thanks for so fast response :)
Yes, I used VisualVM for checking that, and I get 30s working time on this
single method.
I'll try on higher version and I will update this issue.

are you able to post your stub file so that I can attempt to repro?
>

I added request matching in issue, but after some time in debbuger I
noticed that not only this single mapping is used (-> issue #1153).

Best regards.
--
Mateusz Beczek


pon., 8 lip 2019 o 10:26 Tom Akehurst <notifications@github.com> napisał(a):

**Comment by tomakehurst** [comment]
Could you post your VisualVM dump?

I'm not 100% sure what you mean about the request mapping. Are you able to post your entire stub set, rather than just the one example?

Also, to double-check: are you using any custom extensions?

**Comment by mbeczek** [comment]
Hi,
Unfortunately, my company forbids me sharing this.
On the other hand, I upgraded WireMock to newest and works like charm, but still - this condition in _allBodyPatternsMatch_ should be extended to byte array length check for better performance.

**Comment by tomakehurst** [comment]
I'm going to close this, since the immediate performance problem seems to be fixed in recent builds. Noted that matching could be a little more efficient, but I'm probably not going to spot fix this particular issue unless there's a big gain to be had. At some point there'll be a major matcher rewrite with a focus on search efficiency.
