### ISSUE TITLE
Security Vulnerabilities: npm packages and ruby gems

### ISSUE THREAD

**Issue by IAmJoffa** [tomakehurst/wiremock#1235]
WireMock Version: 2.25.1

### Issue Description
There are security vulnerabilities identified by both 'npm audit' and the github security checker for three ruby gems included in the package. The issues are all to do with the docs-v2 part of the project and not necessarily WireMock itself.

I am working on fixing the issues and will do a PR for that very soon. The issues identified by 'npm audit' are listed below.

[audit.txt](https://github.com/tomakehurst/wiremock/files/3948558/audit.txt)

### Fix and Testing
I have run the tests and also run a build. I have also run the new version against our Automation Test harness and it is working ok.

Is there anything else that needs to be done to verify that things are working?

**Comment by tomakehurst** [comment]
WireMock gets automated security vuln PRs etc. occasionally in relation to the docs project.

There are a few reasons I've been reluctant to apply fixes though:
1) There are no automated tests specifically for the docs, and in the past upgrading npm and ruby modules has introduced subtle changes to CSS etc., which are a pain to find and fix.
2) It's just a build-time static site generator project, so I'm struggling to see how any security vuln is really relevant.
3) Any time I upgrade dependency versions in the ruby part of the project I seem to spend half a day just getting the documentation toolchain working again.

If you're happy to manually re-test that the site generator still works, and the generated site looks the same as it did before then please by all means create the change. Otherwise TBH, I'm unlikely to merge it before the next round of CVEs renders the fix obsolete.

**Comment by IAmJoffa** [comment]
No problems, I'm happy to contribute.

Just going through the Docs and also the Swagger-UI links and there are a few subtle changes.

With the Swagger-UI ones I think that they are a result of the swagger project changing things and so nothing that I would expect will be an issue. If you want I'll document these in the PR with some before and after and then you can go through them.

For the Docs part there are changes that look like additions over v2.25.1 as well as some formatting changes in the code/json sections. To me these look like intentional changes to make these more consistent and easier to read. Have a look at this as an example and I can document the rest for the PR so that you can go through them.

An example of the old format for code snippets:

![image](https://user-images.githubusercontent.com/38895588/70665829-82fb6200-1cc1-11ea-9928-6f6153439323.png)

New format for Code snippets:

![image](https://user-images.githubusercontent.com/38895588/70665846-8ee72400-1cc1-11ea-9ff9-399b02126601.png)

There is also a slight spacing change on the API Reference page. This may be to do with the ReDoc update from 2.0.0-rc.2 to 2.0.0-rc.18.

Old page:

![image](https://user-images.githubusercontent.com/38895588/70666013-e5546280-1cc1-11ea-8695-75e9a334eb74.png)

New Page:

![image](https://user-images.githubusercontent.com/38895588/70666038-f56c4200-1cc1-11ea-9f19-71abad7b03eb.png)

**Comment by IAmJoffa** [comment]
PR for this: #1237

**Comment by tomakehurst** [comment]
The first difference (code snippets) is fine, no problem with that.

The 2nd one is a bit ugly. Is this something we can correct in our CSS?

**Comment by IAmJoffa** [comment]
The API reference Page differences might be because I have taken the screen shot at a different size. I'll check this tomorrow and post an update. Please check the PR as I have added lots of info on the few changes to the UI.

**Comment by IAmJoffa** [comment]
I've updated the screen shot in #1237 for the API reference that shows that the margin is correct in the new version. The issue was that I had taken the screen shot at an incorrect size.

**Comment by msbg** [comment]
Many thanks for this - any idea when it will be included in a release?

**Comment by tomakehurst** [comment]
PR merged, thanks!
