### ISSUE TITLE
Undesired response headers for Access-Control-*

### ISSUE THREAD

**Issue by timnederhoff** [tomakehurst/wiremock#1283]
From version 2.26.3, or more specifically, since commit 6e12577cf73567c70b501d9bb399263a62115dc1 the response headers contain Access-Control-Allow-Credentials, also a duplicate one if one is already specified. Also Access-Control-Allow-Origin is set by default from {{request.headers.Origin}}. If I specify a Access-Control-Allow-Origin, a second instance of this header is returned.
Is this feature (returning default headers even if one is already specified) according to the requirements? It looks like a big change in behavour of the application. I wouldn't expect this on a patch level version update.

**Comment by tomakehurst** [comment]
I thought it should really have been enabled in the first place, but I agree it changes behaviour if you're already sending your own from your stubs, and that's not a cool thing to do on a patch release.

I'll look at putting it under config flag in the next minor release.

**Comment by EB123** [comment]
Agree with @timnederhoff , putting it under config flag (as @tomakehurst  already said :smile: ) will be great. 

We are using wiremock to mock an upstream service when we test the CORS functionality of our api-gateway, so until now we had a test that if the service is not marked as "cors enabled" then the `Access-Control-Allow-Origin` header shouldn't be present, and now it always is... so we had hardcode the previous version instead of working with `latest`.
