### ISSUE TITLE
Java security error - UnrecoverableKeyException: Cannot recover key

### ISSUE THREAD

**Issue by JesseKPhillips** [tomakehurst/wiremock#1403]
Upgrading Wiremock results in a failure to read an existing key file. I'm logging this more as informational rather than requesting investigation. I'll continue posting information I've identified about my situation here.

This key file has been functioning for the following versions (currently tested)
* 2.22.0
* 2.26.3

It is not working with these versions (currently tested):
* 2.27.2

Command:
`-jar C:\wiremock-standalone-2.22.0.jar --https-port 11020 --port 10020 --https-keystore C:\keyfile.jks --keystore-password passwordtext  --max-request-journal-entries 512`

Key Generation (Partial code written in D):
```
auto pid = spawnProcess(["openssl", "pkcs12", "-export", "-in", "keyfile.crt", "-inkey", "keyfile.key", "-certfile", "keyfile.crt", "-out", "keyfile.p12"]);

wait(pid);

pid = spawnProcess([javaLocation.buildPath("keytool"), "-importkeystore", "-srckeystore", "keyfile.p12", "-srcstoretype", "pkcs12", "-destkeystore", "keyfile.jks", "-deststoretype", "JKS"]);
```

Some items in research that came up was utilizing different Java versions (32bit vs 64bit) for the generated key and usage, as this is an issue raised by changing the Wiremock version this seems unlikely to be happening.

**Comment by bergerst** [comment]
I debugged a bit and found out that there's a new property in `WiremockConfiguration` called `keyManagerPassword`. So now you have to specify both the keyStorePassword and the keyManagerPassword.

The keyStorePassword is the password of the keystore, while the keyManagerPassword is the password of the keys inside the keystore.

Tomcat's default behavior is to use the keystore password as key password if the key password is not set: https://github.com/apache/tomcat/blob/630adb6272beb02cd709465441e841f2d362b6fb/java/org/apache/tomcat/util/net/SSLUtilBase.java#L278

The JDK System Properties for the keystore and password don't even offer a property for the key password and just assume that it's always the same as the keystore password.

I would suggest implementing the Tomcat logic for Wiremock in order to keep the compatibility.

**Comment by themason** [comment]
@bergerst thanks for this. Adding keyManagerPassword as below totally resolved this issue for me.

```
wireMockRule = new WireMockClassRule(options()
                .port(8081)
                .httpsPort(442)
                .keystorePath(PATH_TO_STORE)
                .keystorePassword("password")
                .keyManagerPassword("password"));
```

**Comment by JesseKPhillips** [comment]
This also fixes the issue on the command line arguments

--https-port 11020 --https-keystore <file> --keystore-password
<password> --key-manager-password <password>
