### ISSUE TITLE
[Security] Handlebars causes CVE-2021-23369

### ISSUE THREAD

**Issue by jamietanna** [tomakehurst/wiremock#1534]
Unfortunately the upstream dependency isn't yet updated, although https://github.com/jknack/handlebars.java/pull/855#pullrequestreview-685189975 has been raised for this.

Once updated, it'd be good to put a release out if possible, due to the nature of this Critical CVE.

**Comment by tomakehurst** [comment]
CVE-2021-23369 refers to the JS version of Handlebars, which isn't used by WireMock. I realise it's embedded in the JAR, but it's never invoked so you're safe to add an exclusion rule.

I'm going to close this because Dependabot will open a PR when there's a new Java version available and there's nothing I can do in the meantime.

**Comment by jamietanna** [comment]
Ah that's good to know, thanks Tom!
