### ISSUE TITLE
parseJson helper won't parse JSON that has an array at the top level

### ISSUE THREAD

**Issue by tomakehurst** [tomakehurst/wiremock#1547]

**Comment by TuxedoFish** [comment]
Giving this a go 👍  http://github.com/TuxedoFish/wiremock/tree/fix-1547-parse-json-helper

**Comment by TuxedoFish** [comment]
In terms of the expected behaviour for a small test case:

`
[
   {
      "key": "value"
   }
]
`

The expected behaviour should be that this returns an ArrayList<Object> with one item which is a Map<String, Object> that contains one key value pair? A test case such as this should then pass but currently fails with an error:

`@Test
    public void parsesJsonWithTopLevelArray() throws Exception {
        String inputJson = "[{\"key\": \"val\"}]";
        Object output = render(inputJson, new Object[]{}, TagType.VAR);

        // Check list returns
        assertThat(output, instanceOf(ArrayList.class));
        ArrayList<Object> result = (ArrayList<Object>) output;
        assertThat(result, hasSize(1));
        // Check inner is a map
        assertThat(result.get(0), instanceOf(Map.class));
        Map<String, Object> inner = (Map<String, Object>) result.get(0);
        assertThat(inner, hasEntry("key", "val"));
    }`

With the error: 

`
"title" : "Error parsing JSON",
"detail" : "Cannot deserialize value of type `java.util.LinkedHashMap<java.lang.String,java.lang.Object>` from Array value (token `JsonToken.START_ARRAY`)"
`
