### ISSUE TITLE
Proxy all for all domains?

### ISSUE THREAD

**Issue by zontreck** [tomakehurst/wiremock#211]
I've recently needed to have a mocking server that will act as a proxy but to literally record the HTTP traffic and play it back another day. So far to accomplish what I'm describing here because of how the content is played back i've had to edit the JSON files and point to another instance of wiremock running on another port. This is not convenient since i'll need to be running at least ten instances to cover the other required sites hosting files needed by this page. If we could simply proxy all the domains at once with maybe proving no arguments, or a wild card to the proxy-all command parameter, that'd be helpful..  So far this program does just about everything i need and can be wrapped into a simple command... I guess if i have to i can edit the program code myself, i just thought maybe others might benefit from this as well. If i need this, what's the chances someone else might too? :)

And this is the standalone i'm referring to.

**Comment by freizl** [comment]
+1.
Currently seems [hoxy](http://greim.github.io/hoxy/) would help to address my problem but it lacks APIs for testing purpose. (add/remove dynamically, verify)

**Comment by tomakehurst** [comment]
Just to ensure I understand the problem correctly: you'd like to be able to use WireMock to host stubs for multiple domains, but because it doesn't expose a virtual host feature, you can't match stubs based on the domain in the URL?

If that's the case, there might be a simple solution. If your clients are well behaved and send a ``Host`` header in each request, you can simply add a ``Host`` header to the request pattern in each of your stubs. Provided all your domains point to WireMock's IP address that should function as a virtual host setup.

Is this any help?

**Comment by zontreck** [comment]
Sorta. What about the ?ts=483726 line in the requests? ( not the real ts line, only a example of the changing time stamps)

**Comment by tomakehurst** [comment]
So you want any URL starting with ``/verify`` to match a particular stub, irrespective of what's in the query parameter?

If that's the case, just use ``"urlPath": "/verify"`` instead of ``url``. That way (unless you explicitly include a ``queryParameters`` section) it'll only match on the URL path.

A ``urlPattern`` (regex) would also work.

**Comment by zontreck** [comment]
I have two domains that have /verify. Both with different content. Is there anyway to separate domains by perhaps, folders?  Making new stubs for each domain that could potentially have the same file is a little much.

**Comment by tomakehurst** [comment]
If your HTTP client is well behaved and sends a ``Host`` header, you can use that to differentiate stubs that need to vary between the domains, and omit it for stubs that should be the same.

**Comment by ravikpilla** [comment]
Here is my issue. I have a Andriod app calling a restAPI(ownAPI.domain.com/item/search) hosted on a VM in cloud (load balanced). the restAPI internally calls another API(otherAPI.Otherdomain.com) hosted on different VM in cloud(load balanced).

I need to automate my UI testing. I cannot guarantee the data from the API on otherAPI.Otherdomain.com. I am trying to mock the call to this API.

I am trying to mock by running a standalone mock instance. With out changing my code how can I get the API call on otherAPI.Otherdomain.com return my mock data. Any thing I have to add in the mappings, files folders for wiremock

Is there a better way to get that done?

Thank you
Ravi
