### ISSUE TITLE
(idea) add support for executing scripts on endpoints calls

### ISSUE THREAD

**Issue by devopsd** [tomakehurst/wiremock#226]
It would be nice to be able to execute scripts (Groovy, JavaScript, etc.) on endpoint calls and have request bound to the scripting engine, so that part of the response can depend for example on path/query params

**Comment by tomakehurst** [comment]
It is now possible in the latest release to transform responses dynamically by writing an extension:
http://wiremock.org/extending-wiremock.html

I wanted to avoid committing WireMock to any specific language or templating engine because there are so many and they tend to be the subject of religious wars.
