### ISSUE TITLE
Add support for RAML (RESTful API Modeling Language)

### ISSUE THREAD

**Issue by RobWin** [tomakehurst/wiremock#235]
An enhancement idea: 
Allow to match Wiremock verifications against a RAML specification (http://raml.org/)
so that I can verify whether my REST Client matches the RAML specification of the REST API.

See https://github.com/ozwolf-software/raml-mock-server. It would be great if WireMock had a similar feature.

**Comment by tomakehurst** [comment]
Just so I understand correctly - you mean you'd like to be able to verify that your WireMock stubs are compliant with a RAML spec?

If so, I think this is a good idea, but possibly not as a core WireMock feature. Given that the project you gave as an example is a separate library outside of Mock Server, do you think the same approach could be taken with WireMock?

**Comment by RobWin** [comment]
I have two ideas. 
* Generate Stubs based in a RAML or Swagger Specification.
* Automatic verification of requests and responses.

**Comment by tomakehurst** [comment]
I think these are both great ideas, and I've been thinking along similar lines recently. I'd like to avoid loading up WireMock with more and more support for specific integration points though (not least because there's demand for Android support for which keeping the core reasonably lean is essential).

It should be possible to implement your first idea as a separate library, just calling WireMock's API to create stubs as usual. Since there's a WireMock API to retrieve stub mappings the second one could probably also be done this way, although this might be made a bit slicker if we added a ``Verifier`` extension point.

**Comment by jmellano** [comment]
Hi,
I am looking for a similar solution to generate wiremock stub based on a swagger specification. Did you create this library or is there no work done on this idea ?

**Comment by arielsegura** [comment]
Hi,
I was looking for that solution too but it doesn't exist. So I've just created this:
https://github.com/arielsegura/raml-java-mock-server/
Hope it works for you guys too.

**Comment by tomakehurst** [comment]
Thanks for sharing! It'd suggest also announcing this on the mailing list.

You might want to take a look at #546 .

**Comment by pjotal** [comment]
@arielsegura do you have any plans to include a command line argument so we can provide the raml url during the initialization of wiremock as a standalone?
