### ISSUE TITLE
addRequestProcessingDelay doesn't work after request then reset

### ISSUE THREAD

**Issue by notclive** [tomakehurst/wiremock#240]
I'm having a problem where `addRequestProcessingDelay` isn't having any effect if it follows a request to the wiremock server and then a reset.

See `https://github.com/notclive/wiremock-reset-delay-bug/blob/master/src/test/java/WiremockResetDelayBugTest.java` for a reproducing test.

If the `expectTimeoutDueToRequestProcessingDelay` test is run alone then it passes.

If both tests are run then the request in `expectTimeoutDueToRequestProcessingDelay` doesn't timeout as expected.

**Comment by tomakehurst** [comment]
I just ran your test with a ``tcpdump`` trace running. It looks like in the first test your HTTP client is creating a TCP connection then caching it and re-using in the second test. Because ``addRequestProcessingDelay`` applies the delay before ``syn/ack``, if you already have a live connection there won't be any delay at all.

You might want to try switching your Jersey client to be backed by the Apache HTTP client and explicitly disable connection pooling in that.

**Comment by notclive** [comment]
Thanks for your time, I'll close this issue.

Would it be reasonable for the wiremock server to disable persistent connections?

**Comment by tomakehurst** [comment]
It's probably technically possible (e.g. by sending Connection: close headers) but generally IMO this is the sort of thing you'd configure client side. Most of the time you'd want pooled connections for performance, so I wouldn't want to prevent this from being possible.

**Comment by coman1977** [comment]
Any news about this feature?

**Comment by coman1977** [comment]
Any news about this feature http://one.wiremock.org/simulating-faults.html
