### ISSUE TITLE
Support predicates/hamcrest matchers in stub configuration

### ISSUE THREAD

**Issue by artkoshelev** [tomakehurst/wiremock#311]
It would be nice to have more flexible way of defining matching expectations instead of urlEquals and urlMatches methods

**Comment by tomakehurst** [comment]
I'm about to push 2.0.5-beta which will support Java 8 lambdas as request matchers.

**Comment by mbjelac** [comment]
while java 8 lambdas are a useful solution, i would still like to have hamcrest supported for matching. there are several reasons:
1. the matchers are already implemented so there's no need to implement our own
2. this would require the user to upgrade to java 8
3. hamcrest matchers have concise failure descriptions, whereas custom matchers would have to implement their own

Here are some examples of why hamcrest matchers would be a more powerful approach:

without hamcrest:
```
verify(
        postRequestedFor(urlMatching("/myApp/.*"))
                .withHeader("accept-encoding", equalTo("gzip")));
```

with hamcrest:
```
verify(
        postRequestedFor(matches("/myApp/.*"))
                .withHeader("accept-encoding", is("gzip")));
```

this would get rid of superfluous matching code in the WireMock lib and also enable more powerful verification such as verification of numeric data:
```
verify(
        postRequestedFor(matches("/myApp/.*"))
                .withHeader("Content-Length", greaterThan(1024)));
```

all matchers in the examples available in the [hamcrest Matchers utility class](http://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/Matchers.html).

**Comment by kbrazulewicz** [comment]
I was very surprised that wiremock doesn't use Hamcrest for matching. Would you accept contribution for that @tomakehurst?

**Comment by tomakehurst** [comment]
It's something I've thought about a few times. I'm not sure I see huge value in it given that the the thing being matched is only ever a single ``Request`` - Hamcrest's generics and collections support aren't much use.

Also, I've been thinking of altering the matching logic to support the notion of scoring misses such that "near misses" can be reported when tests fail. Since Hamcrest models a match as boolean it wouldn't be compatible with this.

**Comment by kovacevicm** [comment]
> I'm not sure I see huge value in it 

Here's where I find it would be very valuable:
- I'm trying to match on POST's request body
- Request body is a set with random ordering

Sorry for beating a dead horse.

**Comment by tomakehurst** [comment]
You can do all that with custom matchers already, optionally using Java 8 lambdas. Hamcrest won't make that any easier.

**Comment by mbjelac** [comment]
If you just need client request verification & stubbing, I recommend you setup a small server which handles HTTP requests so that it calls a method on a http listener mocked with [Mockito](http://mockito.org/). Expose the mock for use in tests. That way, complete verification and stubbing is available through Mockito, along with [Hamcrest matching](http://site.mockito.org/mockito/docs/current/org/mockito/Mockito.html#argument_matchers). Leverage the power of existing libs. Reuse. Be happy! ;)

**Comment by rachelwilson** [comment]
FWIW, I'm using wiremock in Scala (so I cant use java lambdas) and i'd find hamcrest matchers useful for stubs such as

```
stubFor(WireMock.get(urlMatching("/myurl"))
      .withQueryParam("pageSize", greaterThan(1))
```

**Comment by tomakehurst** [comment]
Have you seen the relational matchers already in 2.0-beta?

e.g. 
https://github.com/tomakehurst/wiremock/blob/2.0-beta/src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java#L269

Also, WireMock custom matching relies on a single method interface rather than Java 8 functions explicitly, so I'd guess there must be some way to make this work in Scala i.e. by coercing a lambda to ``RequestMatcher``?
