### ISSUE TITLE
Add support for multiple sequential responses for requests with the same signature

### ISSUE THREAD

**Issue by shollander** [tomakehurst/wiremock#312]
I have a REST client that accesses a service that uses paging to return results. For example I call ```http://someservice.com/data/<id>/page/next``` which will return a new page of results each time. I have used WireMock successfully for testing other web clients, but I don't see any way to use WireMock for this type of scenario. The closest thing that I see is the use of ```Scenarios``` (http://wiremock.org/stateful-behaviour.html), but it does not fit into this use case since I don't have any way to switch between the Scenarios.

I am looking for something similar to what Mockito provides in allowing consecutive calls (http://site.mockito.org/mockito/docs/current/org/mockito/Mockito.html#10)

**Comment by tomakehurst** [comment]
Scenarios will do what you want I think, albeit with slightly verbose syntax.

The way to think about it is a call to a particular stub advances the state, which causes a different one to be served the next time. You can set up a sequence of states in a particular scenario focussed on just one stub.

For ref (as per the README), please could you post future questions like this on the mailing list rather than opening an issue.
