### ISSUE TITLE
No mapping found matching URL

### ISSUE THREAD

**Issue by srividya9** [tomakehurst/wiremock#332]
Hi,

I am new to wiremock. When i tried xml body matching in standalone wiremock-  java -jar wiremock-1.57-standalone.jar --port 8090 --verbose and hit the url http://localhost:8090/with/xmlBody 

I am getting below error in console:
2015-12-11 15:26:22.395 URL /with/xmlBody is match, but method GET is not
2015-12-11 15:26:22.396 No mapping found matching URL /with/xmlBody

And on page:
HTTP ERROR 404
Problem accessing /__files/with/xmlBody. Reason:    NOT_FOUND

Here is my json
{
    "request": {
        "method": "POST",
        "url": "/with/xmlBody",
        "bodyPatterns" : [
			{ "equalToXml" : "<IsEmailExists> <emailID>testsave3036@mailinator.com</emailID> </IsEmailExists>" }
		]
    },
    "response": {
		"status": 200,
        "body" : "<IsEmailExistsResponse><IsEmailExistsResult>false</IsEmailExistsResult></IsEmailExistsResponse>"
    }
}

Please help in resolving this issue.

**Comment by tomakehurst** [comment]
The value in the body pattern you've specified isn't valid XML. Fixing that would probably help.

Since this is a question rather than a bug or feature request, please could you post any further comments on the mailing list please (as per the readme):
https://groups.google.com/forum/#!forum/wiremock-user
