### ISSUE TITLE
Feature Request: Store all response

### ISSUE THREAD

**Issue by todorovhristo** [tomakehurst/wiremock#337]
Is it possible to store responses alongside with the requests? And not only when they are stubbed but also when they are redirected.

**Comment by tomakehurst** [comment]
What's the use case you have in mind?

If it's just for debugging, the 2.0-beta branch logs out requests + responses when verbose is enabled.

**Comment by todorovhristo** [comment]
It's for sure for debugging. I wan't to be able to debug all req/responses to my server, so when something is broken on device, the QA could pretty quick check in logs to see whether the server is returning correct data and even attach it to bug tracker. Moreover we are different departments for Android & iOS, and it is pretty good to check whether both apps follow the same server-request-flow.

It'll be great if I can get the logs as request, via call which filters them.

**Comment by tomakehurst** [comment]
This sounds like a good idea in principle. I've got a long list of unimplemented stuff still to do so I probably won't get a chance to work on it for a while. I'd be happy to merge a PR though.

Having said that, maybe just implementing your own ``Notifier`` might that funnels the verbose log messages off into your own data structure might be enough to satisfy your requirement?

**Comment by todorovhristo** [comment]
Ok I'l give it a try to 2.0 beta - is the binary hosted somewhere or should I build it from source code?

**Comment by tomakehurst** [comment]
It's released on Maven Central: http://search.maven.org/#artifactdetails%7Ccom.github.tomakehurst%7Cwiremock%7C2.0.7-beta%7Cpom

**Comment by todorovhristo** [comment]
I'm now experiencing the problem that --verbose fails for some reason. That's my attempt:

`$ java -jar wiremock-2.0.7-beta.jar --verbose
Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionParser
	at com.github.tomakehurst.wiremock.standalone.CommandLineOptions.<init>(CommandLineOptions.java:80)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:51)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.main(WireMockServerRunner.java:113)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionParser
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
`

Am I doing something wrong, or should I use different beta?

And once again thank you a ton for all the help and for the great work you have accomplished.

**Comment by tomakehurst** [comment]
You need to use the standalone JAR

**Comment by hbrls** [comment]
And FYI, the standalone jar is here [http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/](http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/)

**Comment by kapilag** [comment]
Hello 
Not sure whether i should be asking my question in this particular thread , but as it is somewhat related will go ahead,

I was able to see request , matched definition and responses using notifiers , however that information is too verbose for my particular need, most of the responses which are more than 15 20 lines goes into file and in my particular case i have responses which are minimum 300 lines, now in order to check which file is returning data for a particular response there is lot of noise on the screen(with response data), and there is no way just to print Matched Response definition as everything is in info.(except regex of my own notifier)

Do you think response data should be in debug log level ? Is there any other way to just print Matched Response Definition and Request url ?
