### ISSUE TITLE
wiremock.org.apache.http.conn.HttpHostConnectException

### ISSUE THREAD

**Issue by hinaverma** [tomakehurst/wiremock#340]
Following is the code snippet, this is running fine in my local but when I configure it using Jenkins it is failing every time, irrespective of the port i provide, where am I doing wrong? Please suggest
@Rule
public WireMockRule wireMockRule = 
    new WireMockRule(WireMockConfiguration.wireMockConfig().port(8888)); // No-args constructor defaults to port 8080

@Before
public void setUp(){
    stubFor(get(urlEqualTo("/Path/Get"))
            .willReturn(aResponse()
                    .withStatus(200)
                    .withBody("[1]")));
}

I have configured wiremock rule on 8888 port, have defined all the stub in the @Before method, I have configured @Test which is hitting the external service with the url http://localhost:8888//Path/Get
Every time I am getting this error Connect to localhost:8888 [localhost/127.0.0.1, localhost/127.0.0.1] failed: Connection refused
wiremock.org.apache.http.conn.HttpHostConnectException: Connect to
 localhost:8888 [localhost/127.0.0.1, localhost/127.0.0.1] failed: 
Connection refused

**Comment by bhargav87** [comment]
any resolution for this?????

**Comment by rapasoft** [comment]
I have the same issue, actually, but I don't know how to fix it. On Jenkins, it currently fails occasionally. I will try to investigate.

**Comment by garimacha** [comment]
I am having the same problem on teamcity. Any solution?

**Comment by tomakehurst** [comment]
Please post full details of the problem you're seeing on the mailing list: Source code and full output.

**Comment by rapasoft** [comment]
Unfortunately I am not able to post full source code and output. But I can describe a "workaround" that helped me fixed this issue. 

In my case, I created additional wrapper rule for `WireMockRule` that would only be instantiated in cases where WireMock is actually used and wanted (e.g. not in every case I am expecting that call hits the WireMock server, for example when some parameters are invalid the request is not sent). The important thing is to mention that you need to prevent the *instantiation* of rule, just suppressing rule execution is not enough. I didn't have that much time to investigate why this is a problem, since it looks like prior to rule execution the server is not running yet.

Something like (pseudo code):
```
@Rule
public WireMockWrapperRule rule = new WireMockWrapperRule(options()...);

@Test
@EnableWireMock
public void testSomethingWithWireMock() {
...
}
```
