### ISSUE TITLE
Ignore TLS errors when proxying

### ISSUE THREAD

**Issue by phxql** [tomakehurst/wiremock#352]
Hi,

i'm using Wiremock to proxy communications with a webservice using standalone: `java -jar wiremock-1.57-standalone.jar --proxy-all="https://..." --record-mappings`.

Unfortunatelly the webservice i'm proxying is using a self-signed certificate which has the wrong common name, so wiremock fails when establishing connection:
```
java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: 
[...]
```

Is there a possibility to disable the certificate validation in wiremock? I can't fix the certifate on the webservice.

**Comment by phxql** [comment]
Found the place in the code: in `com.github.tomakehurst.wiremock.http.HttpClientFactory#buildAllowAnythingSSLContext`, `TrustSelfSignedStrategy` is used. This only works when the certificate is indeed self signed, in my case they self-signed a Root CA, and then it fails.

I changed it to: 
```
            return SSLContexts.custom().loadTrustMaterial(null, new TrustStrategy() {
                @Override
                public boolean isTrusted(X509Certificate[] chain, String authType) throws CertificateException {
                    return true;
                }
            }).build();
```

Now it works.

**Comment by tomakehurst** [comment]
Thanks for posting the solution. Would you consider creating a PR for this?

**Comment by phxql** [comment]
Sure.

**Comment by phxql** [comment]
Here it is: https://github.com/tomakehurst/wiremock/pull/355

**Comment by ZiziTheFirst** [comment]
Would you consider backporting this to the 1.x version?

**Comment by tomakehurst** [comment]
What's preventing you upgrading to 2.x?

**Comment by ZiziTheFirst** [comment]
I thought it was still in beta, not sure how mature. Nevertheless, on development environment there's nothing preventing me. On testing environment, where I want to record some communication wit a weirdly misbehaving service to use in unit tests afterwards, there's Java 7 preventing me from doing so.

**Comment by tomakehurst** [comment]
It is, but it's very stable. I'm really just waiting until I can get a big enough chunk of time to wrap up a few loose ends before doing a non beta release.

**Comment by ZiziTheFirst** [comment]
Ok, I'll give it a go. Since it's not that easy to find it and there's no link in the docs to download the 2.x standalone, I'll post the link to the currently newest JAR here for anyone interested: http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/2.0.8-beta/wiremock-standalone-2.0.8-beta.jar (or people can just browse the [parent directory](http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone) to find the latest version).

I just figured that since it can be fixed by just a simple Apache HttpClient configuration, it should be easy to add it to the Java 6 & 7 compatible 1.x server as well...

However, if the development is discontinued and fully focused to 2.x I understand it's not worth it. Thank you for your time anyway, and keep up the great work you are doing with WireMock!

**Comment by tomakehurst** [comment]
Assuming this is OK now.

**Comment by kashifsoofi** [comment]
Hey, is it possible to do the same either though json config or from command line parameter?
Thanks

**Comment by kashifsoofi** [comment]
> I think it might be with `TRUST_ALL_PROXY_TARGETS` or `TRUST_PROXY_TARGET`

For anyone like me, these flags work with ENABLE_BROWSER_PROXYING option, wiremock docker v 2.32.2 seems to work with self signed certificates out of the box.
