### ISSUE TITLE
Build additional artefact for Java 8+, Jetty 9.3 and HTTP/2

### ISSUE THREAD

**Issue by tomakehurst** [tomakehurst/wiremock#407]
To maintain Java 7 support (which the Android community highly value, along with others in orgs that can't upgrade yet) Jetty 9.2 is as high as we can go.

It would be great to start supporting HTTP/2 as soon as possible though, so I propose creating a 2nd standalone JAR artefact in the build, specifically targeting this configuration.

This would probably necessitate splitting the source tree up into core/ java7/ and java8/ (or something along those lines) and composing core/ with one of the other two at build time.

**Comment by dsyer** [comment]
From what I can tell, there's actually not a *very* deep dependency on Jetty for the core features of Wiremock. If we were to split it up along the lines suggested and remove the Jetty dependencies to separate libraries, it would make it possible to use any Servlet container. Probably it would make the "deployed war" option a bit safer as well, since you could be sure that the main code paths do not depend on container code. I'm quite interested in a version that works flexibly with Spring Boot, and just uses the container that the project under test already has, instead of forcing it to use Jetty (i.e. Tomcat 8, Jetty 9, Undertow). I could help with implementing that here or host it somewhere else, but it would probably be a hack until the code is modularlized a bit. I have some proof of concept code that shows the level of hackery required, and it isn't much, so the modularization is probably not too hard.

**Comment by tomakehurst** [comment]
Hi Dave,

Thanks for the offer to help with this.

We've worked pretty hard to isolate the Jetty dependency. A while back I did a scratch refactoring to get it working with the core Java web server, and I got the tests for all the core features passing.

Unfortunately there are a few less-than-obvious things that depend on some combination of Jetty or the Servlet API such as gzipped responses, file serving and fault injection. It would be great to eliminate these dependencies, if only to remove the Servlet API requirement (which seems to be a regular source of difficulty).

Could you elaborate your motivation for wanting to use your own container with it? Is it simply about dependency (in)compatibility, or something else?

I'm just wondering if dropping the Servlet API would solve your problem.

**Comment by dsyer** [comment]
Dropping the Servlet API in the core would help, certainly, but it isn't necessary as a first step. My main objective is to be able to use the "ambient" container in a Spring Boot project, and not have Wiremock pull in conflicting dependencies. I would also like to be able to provide some mock server support (no HTTP) using Wiremock as a DSL. I can already pretty much do the latter since the core `StubMapping` abstraction is clean and JSON-serializable natively, but the former still needs some work to get it done cleanly. Longer term we could look at doing HTTP without even a Servlet container (Spring 5 is coming soon), if the Servlet dependencies were even further abstracted, but there's no need for that yet.

**Comment by tomakehurst** [comment]
Do you object to using the standalone version as a dependency?

The reason I singled out the servlet API is that it's the one thing that can't be shaded in standalone JAR. Fixing that would guarantee you could use the standalone JAR with anything without dependency clashes.

**Comment by dsyer** [comment]
The standalone has shaded stuff in it, so it's not really great to use as a library. I would prefer to use the "regular" jar and exclude dependencies I don't need (that's what I did in my proof of concept experiments). But that's probably not relevant: if you extract the servlet dependencies into a separate jar, then I can use the same strategy.

It would be more useful (and easier in the short term I think) to extract Jetty dependencies and provide a vanilla Servlet-API based implementation. The fact that you can package as a war and deploy as a standalone makes me think this is almost done, and would only take a little push to clean up some tiny tangles.

**Comment by tomakehurst** [comment]
I actually tend to default to the standalone JAR as a dependency these days, but I can see that might not be great if you're concerned about keep your build artefact size down.

So if I understand your proposal correctly - you're suggesting the idea of a build artefact that knows about the servlet API but not Jetty so that it can be deployed into whatever servlet container you happen to be using?

**Comment by dsyer** [comment]
Yes, that about sums it up.

**Comment by tomakehurst** [comment]
OK, that certainly seems like a reasonable idea. Let me give it a little more thought.

**Comment by Sounie** [comment]
I'm hopeful that the proposed approach will also help users of other frameworks which would otherwise have version conflicts - e.g. DropWizard 1.0

**Comment by tomakehurst** [comment]
Dropwizard has quite a few dependencies in common with WireMock. I usually find it easiest to depend on the standalone JAR when I'm writing Dropwizard apps, rather than playing whac-a-mole with Jackson versions.

**Comment by tomakehurst** [comment]
That commit seems to be off the master branch, which has been frozen for a while now. The currently active one is 2.0-beta. I suggest working off that one instead.

Hopefully it'll be back on master in the next few days, but there's still a bit of tidy-up for me to do first.

**Comment by amirhmd** [comment]
hi there Im new to open source and would love to contribute to wiremock Can anyone help me get started? Or is wiremock  for people who are more experienced in open source?

**Comment by tomakehurst** [comment]
Hi Amir,

Great to hear you're interested in helping.

I'm open to anybody contributing to WireMock. Code quality and consistency is really important, so I suggest if you want to get involved it'd be a good idea to familiarise yourself with the codebase and tests.

Once you've done that (unless you have something specific you'd like to work on) I suggest taking a look at the open issues marked as Bug or Feature Request. If there's one you think you could help with, post your proposed solution in the comments and I'll give feedback. Once we've agreed a way forward you can submit your change via the usual PR process.

Cheers,
Tom
