### ISSUE TITLE
Playing back recorded images not working with Facebook's Fresco

### ISSUE THREAD

**Issue by LMojica** [tomakehurst/wiremock#465]
My app uses Fresco to download images from our image server. When I record an image request with WireMock and then try to play back that recorded file, Fresco gives me an "Unknown Image Format" error. I believe that WireMock is not returning the image properly because the recorded image seems to be valid. For example, WireMock will record the image and save the file with a filename such as "example-image.jpg-X8ofk.json". If I use Python's shutil.copyfile() function to copy the recorded file and save it as "example-image.jpg", when WireMock plays that image back, it shows up correctly in my app.

**Comment by tomakehurst** [comment]
So having done a bit of testing locally, it looks like this is just about the filename. I've tried recording a few image files then renaming them to the correct extension and they all open fine (in the OSX previewer app at least).

I'm planning to add some mime type detection so that the correct filename extension can be generated. Do you think this will solve your problem?

**Comment by tomakehurst** [comment]
Fix in f3c16b63f24f9fad9da78a6a2a3e00abd1698868
