### ISSUE TITLE
Distance calculation is having an impact on performance

### ISSUE THREAD

**Issue by albanf** [tomakehurst/wiremock#489]
We are using wiremock to virtualize a SOAP web service. We use record and playback, for about 400 unique requests.

Our tests run 2-3 times slower against wiremock than against the real service.

I ran a profiler, and 85% of the time was spent in com.github.tomakehurst.wiremock.matching.EqualToPattern.normalisedLevenshteinDistance(String, String)

Any way to disable distance calculation? In the record-playback scenario, only exact matches are relevant.

**Comment by tomakehurst** [comment]
This looks like a bug actually. If you're not using near misses, the JUnit rule (which uses them under the hood) or verifications then the distance calc code shouldn't get touched. I'll fix this in the next release.

Can you confirm you're not using any of those?

Also, is there a specific reason you're matching on string equality rather than using ``equalToXml``?

**Comment by albanf** [comment]
I used the standalone jar, with recording and proxying:
`java -jar wiremock-standalone-2.1.11.jar --record-mappings --proxy-all="http://myservice"`
then just playback.

I think the reason the mappings are generated with `equalTo` is that we use Fast Infoset .

I will disable Fast Infoset and check the performance.

**Comment by tomakehurst** [comment]
I've released the fix for this in 2.1.12
