### ISSUE TITLE
What does WireMockRule.failOnUnmatchedStubs do?

### ISSUE THREAD

**Issue by zuckel** [tomakehurst/wiremock#676]
The flag ```failOnUnmatchedStubs``` on WireMockRule is not documented, but from the parameter name I would expect the semantics to be like this: If any of the defined stub mappings was not hit by a request during test execution, then that test should fail.

Now that I had some problems and had a look into the implementation I don't know what this is supposed to do anymore.

@tomakehurst Can you clarify?

**Comment by zuckel** [comment]
After further research, it seems that this was always intended to fail if there were requests that did not match any stub, not the other way around.

In this case I would still consider the implementation bugged because it only triggers if there are any stub mappings declared at all. Some tests not defining stub mappings is not out of the ordinary. I would prefer it to behave the same as
```java
assertThat(wiremock.findAllUnmatchedRequests().size(), is(0));
```

**Comment by tomakehurst** [comment]
That's a fair point. I'll mark this as a bug.

**Comment by eis** [comment]
@tomakehurst if one were to provide a PR for this, should it do something in the effect of

    assertThat(wiremock.findAllUnmatchedRequests().size(), is(0));

or should it "fail if there were requests that did not match any stub, not the other way around"?

**Comment by tomakehurst** [comment]
Yes, it should have roughly that behaviour, but with a couple of differences:

* It needs to (continue to) throw a `VerificationException` not the stock `AssertionError` you'd get from an `assertThat` call.
* The `VerificationException` can be constructed with a list of near misses (and does so presently) so that these can be rendered out to the console. This behaviour needs to be tweaked so that it doesn't break when there are zero stubs (and therefore near misses).

Yeah, perhaps `failOnUnmatchedRequests` is a bit more intuitive. Happy for that to change since it's only a parameter name.

BTW, this parameter is documented here: http://wiremock.org/docs/junit-rule/#unmatched-requests
