### ISSUE TITLE
Documentation could be improved with Spring Boot support

### ISSUE THREAD

**Issue by dsyer** [tomakehurst/wiremock#731]
The docs say

> Currently it is recommended that you use the standalone JAR as a dependency with Spring Boot projects. This avoids a conflict over the Jetty version

and actually that's quite a bad choice, especially if you have Tomcat on your classpath (the default container for Spring Boot apps). It's much better to use [Spring Cloud Contract Wiremock](http://cloud.spring.io/spring-cloud-static/spring-cloud-contract/1.1.2.RELEASE/#_spring_cloud_contract_wiremock).

Elsewhere in the docs (external links) Spring Cloud Contract is mentioned, but only the stubrunner and accurest features. Vanilla Spring Boot integration tests with Wiremock are a lot simpler and more directly consumable by existing Wiremock users.

Also in the external links section is a link to the e-pages RestDocs plugin, which is kind of superseded by   Spring Cloud Contract Wiremock. Not a problem to mention both, but since they do the same thing you should point that out.

**Comment by tomakehurst** [comment]
Could you elaborate why having the standalone version on your classpath is a problem (since it shades Jetty)? Does it cause a Servlet API clash?

I'll update the links to Spring Cloud Contract next time I push the docs, no problem there.

I hadn't spotted spring-cloud-contract-wiremock, so I'll also update the advice to use that. I've been meaning to work on something similar, but you've saved me the effort!

**Comment by dsyer** [comment]
It shades, but it doesn't (or didn't, maybe it changed) relocate anything, so potentially anything can clash. Also, we don't use Jetty by default, so we have to exclude it, and you can't exclude anything from a shaded jar.

**Comment by tomakehurst** [comment]
It now shades basically everything except the Servlet API. The problem you had previously might have been due to the fact in 1.x it was just a classifier on the same artifact and hence shared the same POM. In 2.x it's a dedicated artifact with a minimal POM.

True, you can't exclude Jetty from the shaded JAR, but other than a slightly larger download I don't find that has any impact. The upside of keeping it running on Jetty is that all the fault injection stuff works, whereas you lose that if you attach it to another container.

**Comment by dsyer** [comment]
We have fault injection for Tomcat in Spring Cloud (you would be more than welcome to steal it).

I see that you are relocating all the dependencies (except slf4j) now. The logging one might cause problems sooner or later, but I agree that things are in much better shape now. We can take a look at whether it can be used to replace some of the things we did.

Irrespective of improvements we might make, I believe spring-cloud-contract-wiremock provides the best options for Spring Boot users (so this issue is still valid).

**Comment by tomakehurst** [comment]
Agreed, if it's battle tested with Spring Boot I'm happy to recommend that people use it (especially since you've implemented fault injection). Happy to have that taken off my hands TBH!

**Comment by tomakehurst** [comment]
Closing as I added a signpost in the docs to the Spring Boot WireMock impl a while back.
