### ISSUE TITLE
undertow

### ISSUE THREAD

**Issue by hmalewska** [tomakehurst/wiremock#786]
Hello :)
Is it possible to replace Jetty with undertow?
I use wiremock to stub a few services in performance testing. I can see that wiremock failes before the tested service, so I cannot check performance limits of my service.

**Comment by tomakehurst** [comment]
What makes you believe it's Jetty causing the bottleneck? Do you have any profiling data you can share?

**Comment by hmalewska** [comment]
We have already tested a solution with wiremock with jetty and our own quick solution with undertow.
For example a test: I add 2000 sec delay for a stub and when I run our test I can see:
1. for jetty
<img width="1018" alt="jetty" src="https://user-images.githubusercontent.com/13205643/31934369-3426b038-b8ac-11e7-90bf-d93461ee537a.png">
you can see that metrics look really bad (max delay is 200852 while set was 2000)
and when I run the whole scenario then wiremock failes before our tested service
2. for undertow
<img width="1031" alt="undertow" src="https://user-images.githubusercontent.com/13205643/31934380-3f8d2d80-b8ac-11e7-9d10-ec360484ff32.png">
the results look much better (max delay is 2527 while set 2000)

**Comment by tomakehurst** [comment]
Do you mean you've ported WireMock to Undertow and got the second set of numbers? Or you've written your own Undertow handler and run against that?

I think I can see what the problem might be, and it's not web server related per se. Currently WireMock adds delays synchronously, tying up a worker thread. If you throw a lot of load at it while adding significant delays it'll block all the threads and start queuing requests, leading to high latency numbers and low throughput.

This can be fixed without a web server change, and it's something I've been meaning to work on for a while but haven't had the time. Since Jetty supports async Servlets, my intention is to put delayed responses onto a background scheduler and then serve them async, avoiding the blocking problem.

**Comment by hmalewska** [comment]
It would be great. What's your planned deadline you would like to implement that?

**Comment by tomakehurst** [comment]
I'm afraid I can't commit to deadlines for WireMock stuff. I tend to merge PRs more promptly than working on features from scratch, so if you feel like creating one that would help things along.

**Comment by hmalewska** [comment]
OK, so I'm going to prepare a PR.

**Comment by tomakehurst** [comment]
Great. I've done a bit of thinking about this so I'll post up my thoughts when I'm back at my desk later this afternoon.

**Comment by tomakehurst** [comment]
So I think the solution should be along these lines, but please let me know if you've got a better way in mind!

* Add the delay parameters to the `Response` class so that it's possible to refer to them from within the WireMock servlet
* Add a configuration parameter to specify whether delays should be implemented as they are currently in the response renderer or via the web server's async capability. The reason for making this configurable is that there are other web server implementations out there for WireMock (including undertow) e.g. the ones the Spring Boot project have built. Keeping the option of delays in the response renderer means these impls don't have to do anything to avoid becoming broken.
* When the configuration parameter indicates use of web server async, do not add the delay in `StubResponseRenderer`, and instead do it in `ServletHttpResponder`.
* In `ServletHttpResponder` call `ServletRequest.startAsync()` and use a `ScheduledExecutor` to defer sending the response to the response object in the returned context.

Hope this makes sense.

**Comment by hmalewska** [comment]
Do you think this way? https://github.com/hmalewska/wiremock/pull/1/files

**Comment by jerzykrlk** [comment]
Hi Tom, could you have a look here? https://github.com/jerzykrlk/wiremock/pull/1/files
It's just a few lines' draft for and doesn't include your comments, but all existing tests pass. I'll polish it up a bit later, if you like the general idea.

Btw, I've failed to build Wiremock on Windows and Linux - am I doing something wrong, or does it build only on a mac box?

**Comment by jerzykrlk** [comment]
Hi again. I have a question to your comment:
* I've read the code already - am I right that you're using servlet-api 3 in Wiremock? I'm not 100% sure, but this should ldeally mean, that no matter which web server implementation we're running, the async servlet API should already work fine there?
* here's my idea - I will add the async-servlet-api param for the standalone Wiremock, for now. So that everything works the old way everywhere else. 

What do you think?

**Comment by hmalewska** [comment]
Hi Tom, could you please take a look at the jerzykrlk pull request? I think this is expected solution.

**Comment by tomakehurst** [comment]
Closing, since this is now merged.
