### ISSUE TITLE
newScenarioState not applied if requiredScenarioState not present in matcher

### ISSUE THREAD

**Issue by simonamc** [tomakehurst/wiremock#797]
Working with Wiremock 2.8 we had scenarios of the form

`
  "scenarioName": "Greeting",
  "newScenarioState": "Spanish",
  "request": {
...
  },
  "response": {
`
and this worked well, running against 2.9 / 2.10.1 the state only seems to change if we additionally have the `requiredScenarioState` matcher.  Is this a defect or intended behaviour, the old behaviour gave greater flexibility.

**Comment by simonamc** [comment]
I was just having a look at the code, looks like the logic is in the refactored Scenarios specifically Scenarios#onStubServed.  I think in addition to `scenario.getState().equals(mapping.getRequiredScenarioState()` there needs to be a null check for requiredScenarioState.

**Comment by simonamc** [comment]
Cheers for the swift response and fix.

**Comment by tomakehurst** [comment]
No probs. Nice to get an easy one for a change!

**Comment by jonascoenen005** [comment]
Has this bugg been fixed? Using v2.18.0 and also seeing that NewScenarioState requires requiredScenarioState. I just need to always trigger NewScenarioState when calling a specific service

**Comment by tomakehurst** [comment]
@jonascoenen005 it might help if you upgrade to the latest version. 2.18.0 is pretty old.

**Comment by jonascoenen005** [comment]
@tomakehurst i downloaded the latest jar file from here (http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/2.25.1/wiremock-standalone-2.25.1.jar) and the problem still persists

**Comment by jonascoenen005** [comment]
Ok i've checked what is going wrong in my case: My goal is that when I call a certain service, I want the scenarioState to be set to Started, whichever the current scenarioState is at that moment.

I thought i could easily do it by just dropping the requiredScenarioState, so that it would fall back on my default mapping. This happens indeed for returning the response that has been setup, but the newScenarioState is not triggered because I assume that this one will not be always triggered when the mapping file is being called via the fallback mechanism.

I will try to find another way to reset all the states (I know that calling http://<host>:<port>/__admin/scenarios/reset would work, but in my case I only want to call my services)

Sorry for the inconveniences!
