### ISSUE TITLE
WireMock freeze sometimes

### ISSUE THREAD

**Issue by DzianisH** [tomakehurst/wiremock#955]
Hi,
I have integration test for SpringBoot app with the following configs.

```java
  @Rule
  public WireMockRule mockDataService = new WireMockRule(wireMockConfig()
        .port(5000)
        .usingFilesUnderClasspath("src/itest/resources/"));
``` 
and
```java
  @Before
  public void setUp() {
    mockDataService.stubFor(get("/data/taskXML/full_task.xml")
        .willReturn(ok()
            .withHeader("Content-Type", new MediaType(MediaType.TEXT_XML, Charset.forName("utf-8")).toString())
            .withBody(taskXml)
        )
    );

    mockDataService.stubFor(get(WireMock.urlPathEqualTo("/data/resource/search"))
        .willReturn(WireMock.ok()
            .withHeader("Content-Type", MediaType.APPLICATION_JSON_UTF8.toString())
            .withBody("{\"param\": \"SGVsbG8geW91IGFzc2hvbGUg\"}")
        )
    );
  }
```
And in my test i basically invoke few test cases, and in every test case my domain logic creates two requests in parallel (simultaneously). And sometimes everything works as expected, but sometimes my itest just freeze without any error in log. WireMock thread is in RUNNING status inside some native method. When I go to browser and open any of WireMock endpoints it returns valid response. 
If i add ``mockDataService.start()`` before every test and ``mockDataService.shutdown(); Thread.sleep(1000L);`` after every then the issue reproduces more rarely, but still sometimes appears.

versions:
``org.springframework.boot:spring-boot-starter-parent:2.0.2.RELEASE``
``com.github.tomakehurst:wiremock:2.18.0``

**Comment by tomakehurst** [comment]
There are numerous threads about this on here and the mailing list, so I suggest taking a look at these. The problem is probably that you're starting and stopping your Spring app vs. WireMock on different lifecycles and your HTTP client isn't cleaning up dead connections properly.

Solution is either to switch to using the ClassRule test annotation or using Spring's WireMock support library.

Please post questions on the mailing list going forward.
